[project]
name = "oin-smiles"
version = "0.1.0"
description = "OIN-SMILES: A Python library for generating OIN-SMILES from molecular structures"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ase>=3.26.0",
    "mendeleev>=1.1.0",
    "networkx>=3.4.2",
    "numba>=0.62.1",
    "numpy>=2.2.6",
    "openbabel-wheel>=3.1.1.22",
    "rdkit>=2025.9.3",
    "scine-molassembler>=2.0.0",
    "scipy>=1.15.3",
    "xtb>=22.1",
]

[project.scripts]
oin-smiles = "oinsmiles.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/oinsmiles"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
