from . import om
from . import embed
from . import clean_geometry

def generate_3d_structures(m_smiles, num_conformers=1):
    """
    Generate 3D structures from an m-SMILES string.
    Returns a list of successful geometries as molecule objects.
    """
    try:
        metal_complex = om.get_om_from_modified_smiles(m_smiles)
    except Exception as e:
        print(f"Failed to parse m-SMILES: {e}")
        return []

    cleaner = clean_geometry.TMCOptimizer()
    options = [0, 1]
    scales = [0.8, 0.9, 1.0, 1.1]
    
    successful_mols = []
    
    for scale in scales:
        for option in options:
            if len(successful_mols) >= num_conformers:
                break
                
            positions = embed.get_embedding(metal_complex, scale, option, align=True, use_random=True)
            if positions is not None:
                tmp_complex = metal_complex.copy()
                tmp_complex.set_position(positions)
                
                # cleaner.clean_geometry will print logs, could be silenced later
                success = cleaner.clean_geometry(tmp_complex, scale)
                
                if success:
                    successful_mols.append(tmp_complex.get_molecule())
                    
        if len(successful_mols) >= num_conformers:
            break
            
    return successful_mols

def get_xyz_string(molecule):
    """
    Returns the XYZ string format for a given generated molecule.
    """
    atom_list = molecule.atom_list
    lines = [str(len(atom_list)), f"Generated by MetalloGen-3D, Charge: {molecule.chg}, Multiplicity: {molecule.multiplicity}"]
    for atom in atom_list:
        element = atom.get_element()
        coord = atom.get_coordinate()
        lines.append(f"{element:<3} {coord[0]:>12.8f} {coord[1]:>12.8f} {coord[2]:>12.8f}")
    return "\n".join(lines)
