from . import om
from . import embed
from . import clean_geometry

def generate_3d_structures(
    m_smiles, num_conformers=1, optimizer=None, pool_size=5, ff_params=None
):
    """
    Generate 3D structures from an m-SMILES string.
    Returns a list of successful geometries as molecule objects, sorted by energy if an optimizer is used.

    ff_params: optional dict of TMCOptimizer convergence knobs
    (ff_max_iters, ff_force_tol, ff_energy_tol, d_converge, num_relaxation).
    """
    try:
        metal_complex = om.get_om_from_modified_smiles(m_smiles)
    except Exception as e:
        print(f"Failed to parse m-SMILES: {e}")
        return []

    cleaner = clean_geometry.TMCOptimizer(**(ff_params or {}))
    options = [0, 1, 2] # Added one more option to increase pool variety
    scales = [0.8, 0.9, 1.0, 1.1, 1.2]
    
    # Target number of initial structures to generate
    target_pool = pool_size if optimizer else num_conformers
    successful_mols = []
    
    for scale in scales:
        for option in options:
            if len(successful_mols) >= target_pool:
                break

            # A single scale/option combo can raise inside the embed (e.g. an
            # RDKit valence exception on a dative donor); skip it rather than
            # letting one bad combo abort the whole pool.
            try:
                positions = embed.get_embedding(
                    metal_complex, scale, option, align=True, use_random=True
                )
            except Exception as e:
                print(f"Embedding failed (scale={scale}, option={option}): {e}")
                positions = None
            if positions is not None:
                tmp_complex = metal_complex.copy()
                tmp_complex.set_position(positions)
                
                # cleaner.clean_geometry will print logs, could be silenced later
                success = cleaner.clean_geometry(tmp_complex, scale)
                
                if success:
                    successful_mols.append(tmp_complex.get_molecule())
                    
        if len(successful_mols) >= target_pool:
            break
            
    if not successful_mols:
        return []

    if optimizer:
        from .ml_optimizer import ASEOptimizer
        try:
            opt = ASEOptimizer(method=optimizer)
        except Exception as e:
            print(f"Failed to initialize optimizer '{optimizer}': {e}")
            opt = None
            
        if opt:
            optimized_mols = []
            for mol in successful_mols:
                success, energy, new_mol = opt.optimize(mol)
                if success:
                    optimized_mols.append((energy, new_mol))
                else:
                    # Keep the original if optimization fails but penalize its rank
                    optimized_mols.append((float('inf'), mol))
            
            # Sort by energy
            optimized_mols.sort(key=lambda x: x[0])
            successful_mols = [m[1] for m in optimized_mols]
            
    return successful_mols[:num_conformers]

def get_xyz_string(molecule):
    """
    Returns the XYZ string format for a given generated molecule.
    """
    atom_list = molecule.atom_list
    lines = [str(len(atom_list)), f"Generated by MetalloGen-3D, Charge: {molecule.chg}, Multiplicity: {molecule.multiplicity}"]
    for atom in atom_list:
        element = atom.get_element()
        coord = atom.get_coordinate()
        lines.append(f"{element:<3} {coord[0]:>12.8f} {coord[1]:>12.8f} {coord[2]:>12.8f}")
    return "\n".join(lines)
