import pickle
import time
from concurrent.futures import ProcessPoolExecutor, TimeoutError
import traceback

def _test_worker(args):
    """Minimal picklable worker function."""
    return "Worker output " + str(args)

def _cisplatin_conformer(args):
    """Generate cisplatin using scine_molassembler API."""
    import scine_molassembler as masm
    import scine_utilities as utils
    
    # Cisplatin: PtCl2(NH3)2
    mol = masm.Molecule(utils.ElementType.Pt)
    
    pt = 0
    cl1 = mol.add_atom(utils.ElementType.Cl, pt, masm.BondType.Single)
    cl2 = mol.add_atom(utils.ElementType.Cl, pt, masm.BondType.Single)
    n1 = mol.add_atom(utils.ElementType.N, pt, masm.BondType.Single)
    n2 = mol.add_atom(utils.ElementType.N, pt, masm.BondType.Single)
    
    h1 = mol.add_atom(utils.ElementType.H, n1, masm.BondType.Single)
    h2 = mol.add_atom(utils.ElementType.H, n1, masm.BondType.Single)
    h3 = mol.add_atom(utils.ElementType.H, n1, masm.BondType.Single)
    
    h4 = mol.add_atom(utils.ElementType.H, n2, masm.BondType.Single)
    h5 = mol.add_atom(utils.ElementType.H, n2, masm.BondType.Single)
    h6 = mol.add_atom(utils.ElementType.H, n2, masm.BondType.Single)
    
    # Apply geometry: Square planar
    mol.set_shape_at_atom(pt, masm.shapes.Shape.Square)
    
    # Distance Geometry Generation
    configuration = masm.dg.Configuration()
    results = masm.dg.generate_conformation(mol, 42, configuration)
    
    if isinstance(results, masm.dg.Error):
        return f"DG Exception: {results.message}"
    
    if results is None:
        return "DG Failed to find conformer"
    
    # Get positions - conformer should be a numpy array of shape (N, 3)
    positions = results
    
    # Convert to XYZ format
    output = []
    output.append(str(mol.graph.V))
    output.append("Cisplatin spike generated by molassembler")
    
    for i in range(mol.graph.V):
        elem = mol.graph.element_type(i)
        elem_str = str(elem).split('.')[-1]
        pos = positions[i]
        output.append(f"{elem_str} {pos[0]:.6f} {pos[1]:.6f} {pos[2]:.6f}")
        
    return "\n".join(output)


def main():
    import multiprocessing as mp
    import sys
    
    report = ["# Molassembler Spike Results\n"]
    
    # Task 3: Import check
    try:
        import scine_molassembler as masm
        report.append(f"✅ Import `scine_molassembler` successful.")
        report.append(f"   Version: {getattr(masm, '__version__', 'unknown')}")
        report.append(f"   Import path: `scine_molassembler`")
    except ImportError as e:
        report.append(f"❌ Failed to import `scine_molassembler`: {e}")
        return
        
    # Task 4: Picklability
    try:
        pickled_worker = pickle.dumps(_test_worker)
        report.append(f"\n✅ `_test_worker` is picklable ({len(pickled_worker)} bytes).")
        
        pickled_dg = pickle.dumps(_cisplatin_conformer)
        report.append(f"✅ `_cisplatin_conformer` is picklable ({len(pickled_dg)} bytes).")
    except Exception as e:
        report.append(f"\n❌ Pickling failed: {e}")
        return

    # Task 5: ProcessPoolExecutor basic isolation
    try:
        with ProcessPoolExecutor(max_workers=1) as executor:
            future = executor.submit(_test_worker, {"test": 123})
            result = future.result(timeout=5)
            report.append(f"\n✅ ProcessPoolExecutor minimal test passed: '{result}'")
    except Exception as e:
        report.append(f"\n❌ ProcessPoolExecutor minimal test failed: {e}")

    # Task 6: Cisplatin conformer generation
    def run_generation(queue):
        try:
            res = _cisplatin_conformer({})
            queue.put(res)
        except Exception as e:
            import traceback
            queue.put(f"Exception in worker:\n{traceback.format_exc()}")
            
    print("Testing Cisplatin DG generation...")
    queue = mp.Queue()
    p = mp.Process(target=run_generation, args=(queue,))
    p.start()
    
    p.join(timeout=10)
    
    if p.is_alive():
        print("DG timed out, terminating...")
        p.terminate()
        p.join()
        report.append("\n❌ Cisplatin generation returned error message: DG Timeout (HUNG). Process terminated after 10s.")
    else:
        result = queue.get()
        if "Cisplatin spike generated" in result:
            report.append("\n✅ Cisplatin conformer generated successfully via Molassembler.")
            report.append("API usage:")
            report.append("- masm.Molecule()")
            report.append("- mol.add_atom(utils.ElementType.X)")
            report.append("- mol.add_bond(a, b, masm.BondType.Single)")
            report.append("- mol.set_shape_at_atom(pt, masm.shapes.Shape.Square)")
            report.append("- masm.dg.generate_conformation(mol, seed, conf)")
            
            import os
            os.makedirs("tests/candidate_outputs", exist_ok=True)
            with open("tests/candidate_outputs/spike_cisplatin.xyz", "w") as f:
                f.write(result)
            report.append("\nXYZ written to tests/candidate_outputs/spike_cisplatin.xyz")
        else:
            report.append(f"\n❌ Cisplatin generation returned error message:\n{result}")

    final_report = "\n".join(report)
    print(final_report)
    
    import os
    os.makedirs(".agents/memory", exist_ok=True)
    with open(".agents/memory/molassembler_spike_results.md", "w") as f:
        f.write(final_report)

if __name__ == "__main__":
    main()
