#!/usr/bin/env python3
"""
Generate a PR description from CHANGELOG [Unreleased] block.

Extracts:
  - ## [Unreleased] block (preferred) or most recent version block
  - ### Added, ### Changed, ### Removed subsections

Formats as:
  ## Summary
  - <bullet 1>
  - <bullet 2>

  ## Test plan
  - [ ] <auto-generated from bullets>

Outputs to stdout. Exit code 0 always (graceful fallback to minimal template).
"""

import re
import sys
from pathlib import Path


def parse_changelog(changelog_path):
    """Extract [Unreleased] or most recent versioned block from CHANGELOG.md.

    After hyper-document bumps a version, [Unreleased] becomes empty. This function
    prefers [Unreleased] when non-empty, falls back to the most recent version block.

    Returns: dict with 'added', 'changed', 'removed' keys, each a list of bullets.
    """
    result = {"added": [], "changed": [], "removed": []}

    if not Path(changelog_path).exists():
        return result

    try:
        with open(changelog_path, "r") as f:
            content = f.read()

        # Try [Unreleased] first
        block_match = re.search(
            r"## \[Unreleased\](.*?)(?=## \[|\Z)", content, re.DOTALL
        )

        if block_match:
            block_content = block_match.group(1)
            result = _parse_block_content(block_content)
            # If [Unreleased] has bullets, use it
            if any(result.values()):
                return result

        # [Unreleased] is empty or has no bullets — try most recent version block
        block_match = re.search(
            r"## \[\d+\.\d+\.\d+\](.*?)(?=## \[|\Z)", content, re.DOTALL
        )

        if block_match:
            block_content = block_match.group(1)
            result = _parse_block_content(block_content)
            if any(result.values()):
                return result

        return result
    except Exception:
        return result


def _parse_block_content(block_text):
    """Parse a changelog block's subsections into categories.

    Args: block_text (str) — content between ## headers

    Returns: dict with 'added', 'changed', 'removed' keys, each a list of bullets.
    """
    result = {"added": [], "changed": [], "removed": []}

    current_section = None
    for line in block_text.split("\n"):
        if re.match(r"^### (Added|Changed|Removed)", line):
            current_section = line.split("### ")[1].lower()
        elif line.startswith("- ") and current_section:
            # Remove markdown bold and backticks
            bullet = re.sub(r"\*\*([^*]+)\*\*", r"\1", line[2:].strip())
            bullet = re.sub(r"`([^`]+)`", r"\1", bullet)
            bullet = bullet.rstrip(".")
            if bullet:
                result[current_section].append(bullet)

    return result


def generate_test_plan_items(bullets):
    """Generate test plan checklist items from changelog bullets."""
    items = []

    for bullet in bullets[:5]:  # Limit to 5 items
        # Auto-generate test instructions from bullet text
        if "add" in bullet.lower() or "new" in bullet.lower():
            # For Added items, suggest verifying it works
            test_item = f"Verify the new feature works: {bullet[:50]}..."
        elif "remov" in bullet.lower() or "delete" in bullet.lower():
            # For Removed items, suggest verifying it's gone
            test_item = f"Confirm {bullet[:50]}... is no longer present"
        else:
            # Generic test item
            test_item = f"Verify {bullet[:50]}... behaves correctly"

        items.append(test_item)

    if not items:
        items.append("Manual verification of changes")

    return items


def generate_pr_description(changelog_data):
    """Format changelog data as PR description markdown."""

    all_bullets = (
        changelog_data.get("added", []) +
        changelog_data.get("changed", []) +
        changelog_data.get("removed", [])
    )

    if not all_bullets:
        # Fallback to minimal template
        return (
            "## Summary\n"
            "Update to reflect recent changes.\n\n"
            "## Test plan\n"
            "- [ ] Manual verification of changes\n"
        )

    # Build Summary section
    summary_lines = ["## Summary"]
    for bullet in all_bullets[:10]:  # Limit to 10 bullets in summary
        summary_lines.append(f"- {bullet}")

    # Build Test plan section
    test_plan_items = generate_test_plan_items(all_bullets)
    test_plan_lines = ["## Test plan"]
    for item in test_plan_items:
        test_plan_lines.append(f"- [ ] {item}")

    # Combine sections
    result = "\n".join(summary_lines) + "\n\n" + "\n".join(test_plan_lines) + "\n"
    return result


def main():
    """Main entry point."""
    try:
        changelog_data = parse_changelog("CHANGELOG.md")
        pr_description = generate_pr_description(changelog_data)
        print(pr_description, end="")
        sys.exit(0)
    except Exception as e:
        # Fallback: output minimal template on any error
        fallback = (
            "## Summary\n"
            "Update to reflect recent changes.\n\n"
            "## Test plan\n"
            "- [ ] Manual verification of changes\n"
        )
        print(fallback, end="")
        sys.exit(0)


if __name__ == "__main__":
    main()
