"""L2 DETACHED, step 0: HOW FAR from the metal does the generator put each ligand? Reads only.

The census files 343 molecules / 6.86 pts under ``G_CONSTRUCTION / DETACHED``, 86% of them eta-bound.
v0.4.15 already proved this is not a SELECTION problem (``OIN_ATTACH_RETURN``: 0 gains of 289 --
every conformer in the pool was detached). So the defect is in what the generator BUILDS, and the
first question is a number, not a hypothesis: by how many Angstrom, for which kind of ligand, on
which metals -- and is it different for the molecules that PASS?

METHOD -- no atom mapping between the two structures, deliberately
-----------------------------------------------------------------
Ligands are the connected components of the NON-METAL covalent graph (the same construction as
``oin/coordination.denticity_signature``), matched input <-> generated by molecular formula. For a
ligand with ``k`` contact atoms of element ``e`` in the INPUT, the generated side contributes its
``k`` SHORTEST metal-``e`` distances *within the matched ligand*. ``inflation = mean_gen - mean_in``.
A group is ``eta`` when its contact atoms are bonded to one another (a ring face, an alkene),
``sigma`` otherwise. The contact cutoff is the encoder's own: covalent radii + 0.45 A.

WHAT A BROKEN VERSION WOULD PRINT
---------------------------------
* a formula match that silently pairs the wrong ligands prints a wide, centred inflation for
  EVERYTHING -- so the CONTROL is the verified passes (fault ``NONE``): their inflation must be small
  and their in-band fraction ~1.0, or the instrument is measuring its own mismatches;
* an identity run (``--identity``: input against itself) must print inflation 0.000 and 100% in band;
* unmatched ligands are COUNTED and printed, never dropped.

    <main>/.venv/bin/python tools/v0418/eta_distance_audit.py --out <jsonl>  [--identity]
"""

from __future__ import annotations

import argparse
import csv
import json
import statistics as st
import sys
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve()
sys.path.insert(0, str(HERE.parents[2] / "src"))  # beats PYTHONPATH, which is the point

from oinsmiles.oin.coordination import _PT, CONTACT_SLACK, metal_indices, parse_xyz  # noqa: E402

DATA = Path("/home/tjmustard/Documents/GitHub/OIN-SMILES/tmCAT-tmPHOTO_xyz_dataset")
SWEEP = DATA / "results-v0.4.17-sweep"
COHORT = DATA / "cohort-v0.4.5-5k"
TABLE = DATA / "results-v0.4.17-reattribution" / "attribution_table.tsv"


def _ligands(symbols, coords, metals):
    """Connected components of the non-metal covalent graph -> list of atom-index lists."""
    n = len(symbols)
    r = np.array([_PT.GetRcovalent(s) for s in symbols])
    d = np.linalg.norm(coords[:, None, :] - coords[None, :, :], axis=2)
    adj = d < (r[:, None] + r[None, :] + CONTACT_SLACK)
    np.fill_diagonal(adj, False)
    mset = set(metals)
    parent = list(range(n))

    def find(a):
        while parent[a] != a:
            parent[a] = parent[parent[a]]
            a = parent[a]
        return a

    for i in range(n):
        if i in mset:
            continue
        for j in np.nonzero(adj[i])[0]:
            if j > i and j not in mset:
                ra, rb = find(i), find(int(j))
                if ra != rb:
                    parent[rb] = ra
    comps = defaultdict(list)
    for i in range(n):
        if i not in mset:
            comps[find(i)].append(i)
    return list(comps.values()), d, adj, r


def _groups_in(symbols, lig, metal, d, adj, r):
    """Contact atoms of one input ligand, split by element and labelled eta / sigma."""
    cut = {i: r[metal] + r[i] + CONTACT_SLACK for i in lig}
    contacts = [i for i in lig if d[metal][i] < cut[i]]
    out = []
    for e in sorted({symbols[i] for i in contacts}):
        atoms = [i for i in contacts if symbols[i] == e]
        # eta = some contact atom of this ligand is bonded to another contact atom
        bonded = any(adj[i][j] for i in atoms for j in contacts if j != i)
        out.append(
            {
                "kind": "eta" if bonded and len(contacts) >= 2 else "sigma",
                "elem": e,
                "k": len(atoms),
                "mean_in": float(np.mean([d[metal][i] for i in atoms])),
                "hapticity": len(contacts),
            }
        )
    return out


def compare(in_text: str, gen_text: str):
    """Per-ligand contact groups of the input, measured in the generated structure."""
    sin, cin = parse_xyz(in_text)
    sg, cg = parse_xyz(gen_text)
    if not sin or not sg:
        return {"status": "UNPARSEABLE"}
    m_in, m_gen = metal_indices(sin), metal_indices(sg)
    if not m_in or [sin[i] for i in m_in] != [sg[i] for i in m_gen]:
        return {"status": "METAL_MISMATCH"}
    ligs_in, d_in, adj_in, r_in = _ligands(sin, cin, m_in)
    ligs_gen, d_gen, _adj_gen, r_gen = _ligands(sg, cg, m_gen)
    formula = lambda syms, lig: tuple(sorted(Counter(syms[i] for i in lig).items()))  # noqa: E731
    pool = defaultdict(list)
    for lig in ligs_gen:
        pool[formula(sg, lig)].append(lig)
    groups, unmatched = [], 0
    for mi, mg in zip(m_in, m_gen):
        for lig in ligs_in:
            gi = _groups_in(sin, lig, mi, d_in, adj_in, r_in)
            if not gi:
                continue
            cands = pool.get(formula(sin, lig))
            if not cands:
                unmatched += 1
                continue
            # identical ligands are interchangeable; take the one nearest this metal
            best = min(cands, key=lambda L: min(d_gen[mg][i] for i in L))
            for g in gi:
                ds = sorted(d_gen[mg][i] for i in best if sg[i] == g["elem"])[: g["k"]]
                cut = r_gen[mg] + _PT.GetRcovalent(g["elem"]) + CONTACT_SLACK
                groups.append(
                    {
                        **g,
                        "metal": sin[mi],
                        "mean_gen": float(np.mean(ds)),
                        "inflation": float(np.mean(ds)) - g["mean_in"],
                        "in_band": int(sum(x < cut for x in ds)),
                        "cutoff": float(cut),
                    }
                )
    return {
        "status": "OK",
        "n_metals": len(m_in),
        "unmatched_ligands": unmatched,
        "groups": groups,
    }


def one(mol: str, identity: bool):
    gpath = COHORT / f"{mol}.xyz" if identity else SWEEP / "structures" / f"{mol}_generated.xyz"
    if not gpath.exists():
        return {"molecule": mol, "status": "NO_STRUCTURE"}
    return {"molecule": mol, **compare((COHORT / f"{mol}.xyz").read_text(), gpath.read_text())}


def _q(xs):
    xs = sorted(xs)
    if not xs:
        return "n=0"
    p = lambda f: xs[min(len(xs) - 1, int(f * len(xs)))]  # noqa: E731
    return f"n={len(xs):4d}  median {st.median(xs):+.3f}  p10 {p(0.1):+.3f}  p90 {p(0.9):+.3f}"


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--identity", action="store_true", help="control: the input against itself")
    args = ap.parse_args()

    table = {r["molecule"]: r for r in csv.DictReader(open(TABLE), delimiter="\t")}
    if len(table) != 5000:
        sys.exit(f"ABORT: attribution table has {len(table)} rows")

    def cls(r):
        if r["fault"] == "G_CONSTRUCTION" and r["sub"] == "DETACHED":
            return "DETACHED"
        if r["fault"] == "NONE":
            return "VERIFIED_PASS"
        return "other_FAIL" if r["outcome"] == "FAIL" else "other_false_PASS"

    recs = [one(m, args.identity) for m in sorted(table)]
    status = Counter(r["status"] for r in recs)
    print(f"DENOMINATOR {len(recs)}   status {dict(status)}   identity={args.identity}")
    print(
        f"unmatched ligands: {sum(r.get('unmatched_ligands', 0) for r in recs)} "
        f"in {sum(1 for r in recs if r.get('unmatched_ligands'))} molecules"
    )
    with open(args.out, "w") as fh:
        for r in recs:
            r["class"] = cls(table[r["molecule"]])
            r["eta"] = table[r["molecule"]]["eta"]
            fh.write(json.dumps(r) + "\n")
        fh.write(f"#DONE {len(recs)}\n")

    by = defaultdict(list)
    band = defaultdict(lambda: [0, 0])
    for r in recs:
        for g in r.get("groups", []):
            key = (g["kind"], r["class"])
            by[key].append(g["inflation"])
            band[key][0] += g["in_band"]
            band[key][1] += g["k"]
    print("\ninflation = mean generated M-X distance minus mean input M-X distance, in Angstrom")
    for kind in ("eta", "sigma"):
        print(f"  {kind.upper()} contact groups")
        for c in ("VERIFIED_PASS", "DETACHED", "other_FAIL", "other_false_PASS"):
            a, b = band[(kind, c)]
            frac = f"{100 * a / b:5.1f}%" if b else "  n/a"
            print(f"    {c:17s} {_q(by[(kind, c)])}   atoms still in band {frac}")
    sys.stdout.flush()


if __name__ == "__main__":
    main()
