"""OIN stability regression tests for all 6 known complexes.

Expected OIN strings were generated by XYZToSMILES().convert() with OIN v3.6
(ChiralEncoding active) on 2026-03-04 and saved to tests/candidate_outputs/.
Human-reviewed before promotion to tests/fixtures/.

These are the SHIPPED goldens: they track the default configuration, which as of v0.4.5 has
six canonicality levers ON (see ``oin/levers.py``). Three strings were re-pinned on 2026-07-26,
and each was checked to be a relabeling rather than a new isomer before the golden was touched:

  CisPlatin      [Cl]{0}.[Cl]{1}.N{2}.N{3}  ->  N{0}.N{1}.[Cl]{2}.[Cl]{3}   key IDENTICAL
  TransPlatin    [Cl]{0}.N{1}.[Cl]{2}.N{3}  ->  N{0}.[Cl]{1}.N{2}.[Cl]{3}   key IDENTICAL
  fac-Ir(ppy)3   ...n{3}1...n{1}1...n{4}1    ->  ...n{5}1...n{1}1...n{3}1    key IDENTICAL

``OIN_CANONICAL_SLOTS`` labels vertices by lex-min colour and ``"N" < "[Cl]"`` bytewise, so the
amines take the low slots. Cis is still cis -- the chlorides land on 2,3, which are adjacent --
and ``canonical_roundtrip_key`` is unchanged for all three, which is the assertion that would
have caught a canonicalization that merged two isomers. Cis-PtCl2(en) and mer-Ir(ppy)3 did not
move. The lever-OFF path still reproduces the pre-v0.4.5 bytes exactly; that is pinned
separately in ``test_canonical_body.TestFlagOffIsByteIdentical`` and
``test_canonical_slot_invariance.TestLeverOffIsByteIdentical``.

The BDPP/BDNN backbone tags also changed (``@@/@`` -> ``@/@@``) and there the round-trip key
changes too -- correctly, because the old tags encoded the INVERTED configuration. See
``test_chiral_p``'s module docstring for how that survived four months of a circular oracle.
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../../src")))

from oinsmiles import XYZToSMILES

_FIXTURES = os.path.abspath(os.path.join(os.path.dirname(__file__), "../fixtures"))


def _fixture(filename: str) -> str:
    return os.path.join(_FIXTURES, filename)


class TestRegressionStability(unittest.TestCase):
    """OIN string must be byte-identical on every run for known complexes."""

    def _convert(self, filename: str) -> str:
        return XYZToSMILES().convert(_fixture(filename))

    def test_cisplatin(self):
        self.assertEqual(
            self._convert("CisPlatin.xyz"),
            "[Pt_SPL].N{0}.N{1}.[Cl]{2}.[Cl]{3}",
        )

    def test_transplatin(self):
        self.assertEqual(
            self._convert("TransPlatin.xyz"),
            "[Pt_SPL].N{0}.[Cl]{1}.N{2}.[Cl]{3}",
        )

    def test_cis_ptcl2en(self):
        self.assertEqual(
            self._convert("Cis-PtCl2(en).xyz"),
            "[Pt_SPL].[NH2]{0}CC[NH2]{1}.[Cl]{2}.[Cl]{3}",
        )

    def test_ferrocene(self):
        self.assertEqual(
            self._convert("Ferrocene.xyz"),
            "[Fe_LIN].[cH]{0>}1[cH]{0}[cH]{0}[cH]{0}[cH]{0}1.[cH]{1>}1[cH]{1}[cH]{1}[cH]{1}[cH]{1}1",
        )

    def test_fac_irppy3(self):
        self.assertEqual(
            self._convert("fac-Ir(ppy)3.xyz"),
            "[Ir_OCT].c{0}1ccccc1-c1ccccn{5}1.c{2}1ccccc1-c1ccccn{1}1.c{4}1ccccc1-c1ccccn{3}1",
        )

    def test_mer_irppy3(self):
        self.assertEqual(
            self._convert("mer-Ir(ppy)3.xyz"),
            "[Ir_OCT].c{0}1ccccc1-c1ccccn{3}1.c{1}1ccccc1-c1ccccn{5}1.c{2}1ccccc1-c1ccccn{4}1",
        )


if __name__ == "__main__":
    unittest.main()
