"""OIN stability regression tests for all 6 known complexes.

Expected OIN strings were generated by XYZToSMILES().convert() with OIN v3.6
(ChiralEncoding active) on 2026-03-04 and saved to tests/candidate_outputs/.
Human-reviewed before promotion to tests/fixtures/.
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../../src")))

from oinsmiles import XYZToSMILES

_FIXTURES = os.path.abspath(os.path.join(os.path.dirname(__file__), "../fixtures"))


def _fixture(filename: str) -> str:
    return os.path.join(_FIXTURES, filename)


class TestRegressionStability(unittest.TestCase):
    """OIN string must be byte-identical on every run for known complexes."""

    def _convert(self, filename: str) -> str:
        return XYZToSMILES().convert(_fixture(filename))

    def test_cisplatin(self):
        self.assertEqual(
            self._convert("cisplatin.xyz"),
            "[Pt_SPL].[Cl]{0}.[Cl]{1}.N{2}.N{3}",
        )

    def test_transplatin(self):
        self.assertEqual(
            self._convert("transplatin.xyz"),
            "[Pt_SPL].[Cl]{0}.N{1}.[Cl]{2}.N{3}",
        )

    def test_cis_ptcl2en(self):
        self.assertEqual(
            self._convert("cis_ptcl2en.xyz"),
            "[Pt_SPL].[NH2]{0}CC[NH2]{1}.[Cl]{2}.[Cl]{3}",
        )

    def test_ferrocene(self):
        self.assertEqual(
            self._convert("ferrocene.xyz"),
            "[Fe_LIN].[cH]{0>}1[cH]{0}[cH]{0}[cH]{0}[cH]{0}1.[cH]{1>}1[cH]{1}[cH]{1}[cH]{1}[cH]{1}1",
        )

    def test_fac_irppy3(self):
        self.assertEqual(
            self._convert("fac_irppy3.xyz"),
            "[Ir_OCT].c{0}1ccccc1-c1ccccn{3}1.c{5}1ccccc1-c1ccccn{1}1.c{2}1ccccc1-c1ccccn{4}1",
        )

    def test_mer_irppy3(self):
        self.assertEqual(
            self._convert("mer_irppy3.xyz"),
            "[Ir_OCT].c{0}1ccccc1-c1ccccn{3}1.c{1}1ccccc1-c1ccccn{5}1.c{2}1ccccc1-c1ccccn{4}1",
        )


if __name__ == "__main__":
    unittest.main()
